#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Starting mounty"
    /usr/bin/mounty
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon mounty
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping mounty"
	ps auxww | grep mounty | grep python | awk '{print $2}' | xargs -i kill {}
	rm /tmp/mounty.* 2>/dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon mounty
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 2
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
